#!/usr/bin/env python3
# Overview:
# Plot the Figure 4 parameter-scaling panels from a CSV generated by
# collect_parameter_scaling.py. The CSV encodes task panel, model family,
# parameter count, and test relative L2 for each trained checkpoint.
from __future__ import annotations

import argparse
import csv
import sys
from collections import defaultdict
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from helmholtz_hybrid.runtime import set_default_cache_dirs

set_default_cache_dirs()

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker


PANELS = ("Smooth", "Residual", "Sharp")
MODELS = ("FNO", "scOT", "Hybrid")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot Figure 4 parameter scaling from a metrics CSV.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--metrics-csv",
        type=Path,
        required=True,
        help="CSV with at least panel, model, parameters, and rel_l2 columns.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("outputs/figures/parameter_scaling.png"),
        help="Output PNG path for the parameter-scaling figure.",
    )
    return parser.parse_args()


def load_rows(path: Path) -> dict[tuple[str, str], list[tuple[float, float]]]:
    """Validate and group CSV rows by figure panel and model label."""

    grouped: dict[tuple[str, str], list[tuple[float, float]]] = defaultdict(list)
    with path.open(newline="") as handle:
        reader = csv.DictReader(handle)
        required = {"panel", "model", "parameters", "rel_l2"}
        missing = required.difference(reader.fieldnames or [])
        if missing:
            raise ValueError(f"{path} is missing columns: {sorted(missing)}")

        for row in reader:
            panel = row["panel"]
            model = row["model"]
            if panel not in PANELS:
                raise ValueError(f"Unknown panel '{panel}'. Expected one of {PANELS}.")
            if model not in MODELS:
                raise ValueError(f"Unknown model '{model}'. Expected one of {MODELS}.")
            grouped[(panel, model)].append((float(row["parameters"]), float(row["rel_l2"])))

    for values in grouped.values():
        values.sort(key=lambda item: item[0])
    return grouped


def main() -> None:
    args = parse_args()
    grouped = load_rows(args.metrics_csv)

    # Width ratios mirror the paper layout: smooth and residual are compact, and
    # the sharp panel leaves space for the extra hybrid curve.
    fig, axes = plt.subplots(
        1,
        3,
        figsize=(12, 4),
        sharey=True,
        gridspec_kw={"width_ratios": [1, 1, 2]},
        tight_layout=True,
    )

    for ax, panel in zip(axes, PANELS):
        # Missing curves are allowed so partial sweeps can still be plotted.
        for model in MODELS:
            values = grouped.get((panel, model), [])
            if not values:
                continue
            params, rel_l2 = zip(*values)
            ax.plot(params, rel_l2, "-o", label=model)
        ax.set_title(panel)
        ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _pos: f"{x / 1e6:g}"))

    axes[0].set_ylabel("Relative L2 error on test set")
    fig.supxlabel("Millions of parameters")
    handles, labels = axes[-1].get_legend_handles_labels()
    if handles:
        axes[-1].legend(handles, labels, loc="best")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(args.output, dpi=300, bbox_inches="tight")


if __name__ == "__main__":
    main()
